config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :bookings, only: [:index, :destroy]
  # resources :reviews, except: [:new, :create]
  resources :cars do
    resources :bookings
    resources :reviews, only: [ :new, :create ]


  end



  devise_scope :user do
    authenticated :user do
      root "cars#index", as: :authenticated_root
    end
    unauthenticated do
      root "pages#home", as: :unauthenticated_root
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
  validates :start_date, presence: true
  validates :end_date, presence: true
  has_many :reviews
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  validates :model, presence: true
  has_one_attached :photo
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: :destroy
  before_action :set_car, only: [:new, :create]

  def index
    @bookings = Booking.all
    @review = Review.new
  end

  def new
    @booking = Booking.new
  end

  # def show

  # end

   def create
    @booking = Booking.new(booking_params)
    @booking.car = @car
    @booking.user = current_user
      if @booking.save
        redirect_to bookings_path
      else
        render :new
      end
   end

  def destroy
    @booking.destroy
    redirect_to bookings_path(@booking.car)
  end

    private
  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_car
    @car = Car.find(params[:car_id])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    if params[:query].present?
      @query = params[:query]
      @cars = Car.where("name iLike '%#{params[:query]}%'")
    else
      @cars = Car.all
    end
  end

  def show
    @car = Car.find(params[:id])
    @booking = Booking.new
    @reviews = Review.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @user = current_user.id
    @car.user_id = @user
    if @car.save!
      redirect_to cars_path
    else
      render :new
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
    redirect_to cars_path
    flash[:alert] = "Car Updated."
  end
  private

  def car_params
    params.require(:car).permit(:model, :price, :photo)
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
    # @booking = Booking.find(params[:booking_id])
    @car = Car.find(params[:car_id])
  end

  def create

    @car = Car.find(params[:car_id])
    @review = Review.new(review_params)
    @review.car = @car

    if @review.save
      redirect_to car_path(@car)
    else
      redirect_to bookings_path
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<%# <br>
<div class="cards">

  <% @bookings.each do |booking| %>
    <%# <% if booking.user_id == current_user.id %>
      <%# <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8Mnx8fGVufDB8fHx8&w=1000&q=80)">
        <%= booking.start_date %>
        <%# <br>
        <%= booking.end_date %>
        <%# <br>

      </div>
        <%= link_to "delete", booking_path(booking), method: :delete, data: { confirm: "Are you sure you want to remove?"}, class: 'text-danger' %>
    <%# <% end %>
  <%# <% end %>
<%# </div> %>


<!doctype html>
<html lang="en">
    <head>
    <br>
    <br>
        <title>Bookings</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="css/style.css">
	</head>
	<body>
	<div class="background-img"></div>
	<section class="ftco-sections">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="table-wrap">
						<div class="row justify-content-center">
							<div class="col-md-6 text-center mb-5">
								<h2 class="heading-section">Bookings</h2>
							</div>
						</div>
						<table class="table">
						<thead class="thead-primary">
						<tr>
                <th>Booking Number</th>
                <th>Car</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Price</th>
						</tr>
						</thead>
					<tbody>
					<% count = 1  %>
					<% @bookings.reverse_each do |booking| %>
					<% if booking.user_id == current_user.id %>
						<tr class="text-color">
						<th scope="row"><%= count  %></th>
						<% count += 1 %>
            <td><%= booking.car.model%></td>

						<td><%= booking.start_date%></td>

						<td><%= booking.end_date%></td>
            <% day = booking.end_date - booking.start_date %>
            <% day_num = day.to_i %>
            <% fee = day_num * booking.car.price %>
            <td>$ <%= fee.to_i %></td>
            <td>


            <%= link_to "Add Review",   new_car_review_path(booking.car_id), class: "btn btn-outline-primary rounded-start" %>
            <%= link_to "delete", booking_path(booking), method: :delete, data: { confirm: "Are you sure you want to remove?"}, class: 'btn btn-outline-warning rounded-end' %>

            </td>

						</tr>
						<% end %>
					<% end %>
						</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</section>

	<%# <script src="js/jquery.min.js"></script>
    <script src="js/popper.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/main.js"></script> %>

	</body>
</html>

app/views/cars/edit.html.erb
<br>
<br>
<br>
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="car-form form-book p-4 border border-3 shadow-lg">
        <h1 class="text-center fs-1"> Edit your Car</h1>
        <div class="mt-3">
          <%= simple_form_for(@car) do |f| %>
            <div class="form-group p-2">
              <%= f.label :model %>
              <%= f.text_field :model, class: 'form-control' %>
            </div>
            <div class="form-group p-2">
              <%= f.label :price %>
              <%= f.number_field :price, class: 'form-control' %>
            </div>
          
            <div class="mt-3 p-2">
                <%= f.submit class: 'btn btn-primary d-grid gap-2 col-6 mx-auto my-2 rounded-3' %>
                <%= link_to 'Cancel', cars_path, class: 'btn btn-outline-warning d-grid gap-2 col-6 mx-auto my-2 rounded-3' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<%# <%= f.input :photo, as: :file, required: true, class:"form-control form-control-lg" %>

app/views/cars/index.html.erb
<div class="container">
  <br>
  <div>
    <div class="cards">
      <% @cars.reverse_each do |car| %>
        <div class="card-trip">
          <%= cl_image_tag car.photo.key,crop: :fill %>
          <div class="card-trip-infos">
            <div>
              <h2><%= car.model %></h2>
              <p></p>
            </div>
            <h2 class="card-trip-pricing">$<%= car.price %></h2>
          </div>
          <div class = "text-center" style="background-color: rgba(228, 228, 228, 0.596);">
            <%= link_to "Book now", car_path(car), class: "btn btn-flat text-center" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/new.html.erb
<br>
<br>
<br>
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="car-form form-book p-4 border border-3 shadow-lg">
        <h1 class="text-center fs-1">Add a new Car</h1>
        <div class="mt-3">
          <%= simple_form_for(@car) do |f| %>
            <div class="form-group p-2">
              <%= f.label :model %>
              <%= f.text_field :model, class: 'form-control' %>
            </div>
            <div class="form-group p-2">
              <%= f.label :price %>
              <%= f.number_field :price, class: 'form-control' %>
            </div>
            <div class="form-group p-2">
              <%# <%= f.label :picture_url %>
              <%= f.input :photo, as: :file %>
              <%# <%= f.text_field :picture_url, class: 'form-control' %>
            </div>
            <div class="mt-3 p-2">
                <%= f.submit class: 'btn btn-primary d-grid gap-2 col-6 mx-auto my-2 rounded-3' %>
                <%= link_to 'Cancel', cars_path, class: 'btn btn-outline-warning d-grid gap-2 col-6 mx-auto my-2 rounded-3' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<%# <%= f.input :photo, as: :file, required: true, class:"form-control form-control-lg" %>

app/views/cars/show.html.erb
<%# <div class="container margin-top-negative p-5">
  <div class="row">
    <div class="col-8">
      <div class="car-show-card">
        <h1><%= @car.model %></h1>
        <%# <p class="car-show-address"><%= @car.price</p> %>
      <%# </div>
      <div class="car-show-card">
          <%= cl_image_tag @car.photo.key, width: 200, height: 200, crop: :fill %>
      <%# </div>
    </div>

    <div class="col-4 mt-5">
      <div class="car-show-card mt-5">
        <h5>Book this Car</h5>

        <div>
        <p class ="center">New Booking Form</p>

        <div>
      </div>
      <div class="car-show-card">
        <h3>Price</h3>
        <div class="flex">
          <div class="flex ml-3">
            <i class="material-icons mr-2">$</i>
          <%# </div>
        </div>
      </div>
    </div>
  </div>
</div> %>
<div class="row g-0">
  <div  class="col-sm-6 col-md-8">
    <br>
    <br>
    <br>
    <div>

      <%= cl_image_tag @car.photo.key, crop: :fill, class: "shadow-lg img-fluid" %>

    </div>

    <div>
      <br>
      <div class="d-grid gap-2 col-6 mx-auto">
        <%= link_to "Edit your car", edit_car_path, class: "btn btn-ghost" %>
      </div>
      <br>
      <h1>Reviews :</h1>
      <% @reviews.each do |review| %>
        <% if review.car_id == @car.id %>
          <div class="card-product shadow">
            <div class="card-product-infos">
              <ul class = "pt-3">
                <li><h2> <%= review.comment %></h2></li>
              </ul>
              <p class = "ps-3 pb-3" >Rating : <%= review.rating.to_i%> out of 5</i> </p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="col-6 col-md-4 ps-3">
    <br>
    <br>
    <br>
    <h1 class= "text-center">Cost per day</h1>
    <h1 class= "text-center">$ <%= @car.price %></h1>
    <br>
    <br>
    <h2>Book for</h2>

    <%= simple_form_for [@car, Booking.new] do |f| %>
      <%= f.input :start_date %>
      <br>
      <%= f.input :end_date %>
      <br>

      <%= f.button :submit, "Book Me" , class: "btn btn-success  d-grid gap-2 col-6 mx-auto my-2 rounded-3" %>
      <%= link_to  "Back", cars_path , class: "btn btn-outline-warning  d-grid gap-2 col-6 mx-auto my-2 rounded-3" %>
    <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarRental</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.2/js/bootstrap.min.js">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <div class="bg-img"style="background-image: url('https://mdbcdn.b-cdn.net/img/new/slides/003.webp');">
    <%= render 'shared/navbar' %>

  </div>

   <div class="container">
      <%= yield %>
   </div>

  </body>
</html>

app/views/pages/home.html.erb
<div class="background-x">
<br>
  <div class="container">
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="https://www.1auto.co/storage/ready_for_sales/20220217191251_photo-1552519507-da3b142c6e3d.jpg" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block" style="margin-bottom: 300px; font-size:50px; font-weight:bolder; color: white;">
            <h1>Car Rental</h1>
            <p>Make your trips better</p>
            <a href="#" class="btn btn-outline-light" style="font-weight:bold; font-size:20px;">Book now</a>
          </div>
        </div>
        <div class="carousel-item">
          <img src="https://di-uploads-pod14.dealerinspire.com/houseofcarscalgary/uploads/2018/08/2006-Lamborghini-Gallardo-House-of-Cars-Macleod-Trail-768x512.jpg" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block" style="margin-bottom: 300px; font-size:50px; font-weight:bolder;">
            <h1>Car Rental</h1>
            <p>Make your trips better</p>
            <a href="#" class="btn btn-outline-light" style="font-weight:bold; font-size:20px;">Book now</a>
          </div>
        </div>
        <div class="carousel-item">
          <img src="https://hips.hearstapps.com/amv-prod-gp.s3.amazonaws.com/gearpatrol/wp-content/uploads/2019/10/Buy-a-Kia-Telluride-Instead-gear-patrol-slide-1.jpg" class="d-block w-100" alt="...">

          <div class="carousel-caption d-none d-md-block" style="margin-bottom: 300px; font-size:50px; font-weight:bolder;">
            <h1>Car Rental</h1>
            <p>Make your trips better</p>
            <a href="#" class="btn btn-outline-light" style="font-weight:bold; font-size:20px;">Book now</a>

          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
  <br>
  <br>
  <div class="container">
    <h2 class="text-center">How it Works</h2>
    <div class="cards">

      <div class="card text-center">
        <i class="fa-solid fa-envelope my-4" style= "font-size:50px"></i>
        <h4>Sign Up</h4>
        <p>Fast and Easy. Only your email and phone number required.</p>
      </div>

      <div class="card text-center">
        <i class="fa-solid fa-magnifying-glass my-4" style= "font-size:50px"></i>
        <h4>Check our Catalogue</h4>
        <p>There is a car for every rider, trust us.</p>
      </div>

      <div class="card text-center">
        <i class="fa-solid fa-car my-4" style= "font-size:50px"></i>
        <h4>Book a Car</h4>
        <p class= "px-1">In less than 5 taps, rent a car and get going.</p>
      </div>

    </div>
  </div>

  <div class="container">
    <div class="footer">
      <div class="footer-text mt-4">
        <div class="icons text-center" style= "font-size:30px">
          <a class= "i" href="https://www.facebook.com"><i class="fa-brands fa-facebook mx-2" style= "color:black"></i></a>
          <a href="https://www.instagram.com"><i class="fab fa-instagram mx-2" style= "color:black"></i></a>
          <a href="https://www.youtube.com"><i class="fab fa-youtube mx-2" style= "color:black"></i></a>
          <a href="https://www.snapchat.com"><i class="fab fa-snapchat mx-2" style= "color:black"></i></a>
        </div>
      </div>
    </div>


  </div>

</div>

app/views/reviews/new.html.erb
<br>
<br>
<br>
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="car-form form-book p-4 border border-3 shadow-lg">
        <h1 class="text-center fs-1">Add Review</h1>
        <div class="mt-3">
          <%= simple_form_for [@car, @review] do |f| %>
              <br>
              <%= f.input :comment %>
              <br>
              <%= f.input :rating %>
              <br>

              <%= f.button :submit, "Review" , class: "'btn btn-primary d-grid gap-2 col-6 mx-auto my-2 rounded-3" %>
              <%= link_to  "Back", bookings_path , class: "btn btn-outline-warning d-grid gap-2 col-6 mx-auto my-2 rounded-3" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<%# <%= f.input :photo, as: :file, required: true, class:"form-control form-control-lg" %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="background-color:#BF8B67">
  <div class="container-fluid">
    <%= link_to cars_path, class: "navbar-brand " do %>
      <%= image_tag "https://img.favpng.com/24/16/3/auto-show-car-logo-drawing-png-favpng-hsuTVrxAju2vZvhZb9P63g38e.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", cars_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://us.123rf.com/450wm/tuktukdesign/tuktukdesign1608/tuktukdesign160800043/61010830-user-icon-man-profile-businessman-avatar-person-glyph-vector-illustration.jpg?ver=6", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Add car", new_car_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>